export const wholesalersData = {
  SA: [
    "KASTA Technologies (AU) Pty Ltd",
    "GUYMIN PTY LTD",
    "CNW Pty Ltd---BEVERLEY (SA)",
    "CNW Pty Ltd---EDWARDSTOWN (SA)",
    "CNW Pty Ltd---KENT TOWN (SA)",
    "CNW Pty Ltd---LONSDALE (SA)",
    "CNW Pty Ltd---POORAKA (SA)",
    "EMBERTEC PTY LTD",
    "L&H---Adelaide (SA)",
    "L&H---Berri (SA)",
    "L&H---Clovelly Park (SA)",
    "L&H---Gawler (SA)",
    "L&H---MAGILL (SA)",
    "L&H---Kilkenny {DRK} (SA)",
    "L&H---Klemzig (SA)",
    "L&H---Thebarton {DRM} (SA)",
    "L&H---Lonsdale (SA)",
    "L&H---Melrose Park (SA)",
    "L&H---MOUNT BARKER (SA)",
    "L&H---MOUNT GAMBIER (SA)",
    "L&H---MURRAY BRIDGE (SA)",
    "L&H---Nuriootpa (SA)",
    "L&H---PORT ADELAIDE (SA)",
    "L&H---PORT AUGUSTA (SA)",
    "L&H---Port Lincoln (SA)",
    "L&H---Port Pirie (SA)",
    "L&H---Salisbury South (SA)",
    "L&H---SEAFORD (SA)",
    "L&H---ST AGNES (SA)",
    "L&H---WHYALLA {DRZ} (SA)",
    "L&H[AUSLEC]---ROXBY DOWNS {DSB} (SA)",
    "L&H---WINGFIELD (SA)",
    "Lucesco Lighting",
    "MIDDYS---HINDMARSH (SA)",
    "MIDDYS---SALISBURY NORTH (SA)",
    "MIDDYS---SOMERTON PARK (SA)",
    "MIDDYS---STEPNEY (SA)",
    "MMEM---Berri (SA)",
    "MMEM---EDWARDSTOWN (SA)",
    "MMEM---HINDMARSH (SA)",
    "MMEM---KADINA (SA)",
    "MMEM---KENT TOWN (SA)",
    "MMEM---KLEMZIG (SA)",
    "MMEM---Lonsdale (SA)",
    "MMEM---MARLESTON (SA)",
    "MMEM---MOUNT BARKER (SA)",
    "MMEM---MOUNT GAMBIER (SA)",
    "MMEM---MURRAY BRIDGE (SA)",
    "MMEM---NARACOORTE (SA)",
    "MMEM---PORT ADELAIDE (SA)",
    "MMEM---PORT LINCOLN (SA)",
    "MMEM---PORT PIRIE (SA)",
    "MMEM---SALISBURY SOUTH (SA)",
    "MMEM---TANUNDA (SA)",
    "MMEM---VICTOR HARBOR (SA)",
    "MMEM---WAIKERIE (SA)",
    "MMEM---WHYALLA (SA)",
    "MMEM[HAYMANS]---Blair Athol (SA)",
    "MMEM[HAYMANS]---Ferryden Park (SA)",
    "MMEM[HAYMANS]---Hendon (SA)",
    "MMEM---Holden Hill (SA) formerly Haymans",
    "MMEM[HAYMANS]---Marleston (SA)",
    "P&R---BRIGHTON (SA)",
    "P&R---EDWARDSTOWN (SA)",
    "P&R---GAWLER (SA)",
    "P&R---GILLES PLAINS (SA)",
    "P&R---GOOLWA (SA)",
    "P&R---HAHNDORF (SA)",
    "P&R---LONSDALE (SA)",
    "P&R---MALVERN (SA)",
    "P&R---OSBORNE (SA)",
    "P&R---PORT ADELAIDE (SA)",
    "P&R---PORT LINCOLN (SA)",
    "P&R---RICHMOND (SA)",
    "P&R---SEAFORD (SA)",
    "P&R---NORWOOD (SA)",
    "P&R---UNDERDALE (SA)",
    "P&R---POORAKA (SA)",
    "REXEL---ADELAIDE (SA)",
    "REXEL---BERRI (SA)",
    "REXEL---Energy Solutions SA (SA)",
    "REXEL---HINDMARSH (SA)",
    "REXEL---LONSDALE (SA)",
    "REXEL---EDWARDSTOWN (SA)",
    "REXEL---MOUNT BARKER (SA)",
    "REXEL---MOUNT GAMBIER (SA)",
    "REXEL---WINGFIELD (SA)",
    "REXEL---PORT PIRIE (SA)",
    "REXEL---ROXBY DOWNS (SA)",
    "REXEL---SA Major - Projects (SA)",
    "REXEL---SALISBURY PLAIN (SA)",
    "REXEL---WINDSOR GARDENS (SA)",
    "Strike A Light Blackwood",
    "SHERRIFF---KLEMZIG (SA)",
    "SPARKY SUPPLIES PTY LTD",
    "VG ELECTRICAL---FINDON",
    "Cash Sale SA",
    "Haneco Lighting Internal Use SA",
    "Maximum Lighting Pty Ltd",
    "Zheng Tang Pty Ltd",
    "GREEN TARGET AUSTRALIA",
    "Fixed Asset Sale Account",
    "REXEL---PROJECT (SA)",
    "L&H[PDC]---THEBARTON{DWF} (SA)",
    "Green Path",
    "Electricalxpress Pty Ltd",
    "Leaders Migration & Education Pty Ltd",
    "QuantumNet",
    "Future Trade Supplies",
    "Pellegrino Services Pty Ltd",
    "Tradezone SA",
    "REXEL---EDWARDSTOWN SA DC (SA)",
    "MMEM[Greentech]---Hendon (SA)",
    "Blackwoods Whyalla"
  ],
  VIC: [
    "ACTIVE ELECTRICAL DISTRIBUTORS PTY LTD",
    "AED---BALLARAT (VIC)",
    "AED---BAYSWATER (VIC)",
    "AED---BENDIGO (VIC)",
    "AED---COLLINGWOOD (VIC)",
    "AED---GEELONG (VIC)",
    "AED---GOLDEN SQUARE (VIC)",
    "AED---MOORABBIN (VIC)",
    "AED---MORWELL (VIC)",
    "AED---PORT MELBOURNE (VIC)",
    "AED---PROJECT ORDERS (VIC)",
    "AED---SHEPPARTON (VIC)",
    "AED---THOMASTOWN (VIC)",
    "Appselec Pty Ltd",
    "Aussie Greenmarks",
    "Blackwoods Melbourne",
    "Blackwoods Morwell",
    "BUCKFORD ILLIMINATION GROUP PTY LTD",
    "Calmatronics Pty Ltd",
    "Cash Sale VIC",
    "Cetnaj West Pty Ltd---AIRPORT WEST (VIC)",
    "Cetnaj West Pty Ltd---SUNSHINE (VIC)",
    "Cetnaj West Pty Ltd---THOMASTOWN (VIC)",
    "CNW Pty Ltd---BALLARAT (VIC)",
    "CNW Pty Ltd---CLAYTON (VIC)",
    "CNW Pty Ltd---CLYDE NORTH (VIC)",
    "CNW Pty Ltd---CROYDON (VIC)",
    "CNW Pty Ltd---ENERGY CLAYTON (VIC)",
    "CNW Pty Ltd---GEELONG (VIC)",
    "CNW Pty Ltd---SCORESBY {KNOXFIELD} (VIC)",
    "CNW Pty Ltd---SOUTH MELBOURNE (VIC)",
    "Delta Electrical Distributors",
    "Delta Electrical Distributors Bendigo",
    "Delta Electrical Distributors Shepparton",
    "Delta Electrical Distributors Thomastown",
    "DELTA---BENDIGO (VIC)",
    "DELTA---SHEPPARTON (VIC)",
    "DELTA---THOMASTOWN (VIC)",
    "Eastern Services Group Pty Ltd",
    "Encompass Integration",
    "Go Electrical---Airport West (VIC)",
    "Go Electrical---Airport West (VIC)",
    "Go Electrical---Campbellfield (VIC)",
    "Go Electrical---Campbellfield (VIC)",
    "Go Electrical---Doveton (VIC)",
    "Go Electrical---Eltham (VIC)",
    "Go Electrical---Eltham (VIC)",
    "Go Electrical---Heidelberg West (VIC)",
    "Go Electrical---Port Melbourne (VIC) formerly Southbank",
    "Go Electrical---Port Melbourne (VIC) formerly Southbank",
    "Go Electrical---West Heidelberg (VIC)",
    "Greaton Development Pty Ltd",
    "Haneco Lighting Internal Use VIC",
    "Intellispec Pty Ltd",
    "J&S Electricals (Aust) Pty Ltd",
    "L&H GROUP PTY LTD",
    "L&H[ALCOA]---PORTLAND (VIC)",
    "L&H[AUSLEC]---CAMPBELLFIELD (VIC)",
    "L&H[AUSLEC]---DOVETON (VIC)",
    "L&H[AUSLEC]---LILYDALE (VIC)",
    "L&H[AUSLEC]---SUNSHINE (VIC)",
    "L&H[PDC]---KNOXFIELD (VIC)",
    "L&H[PDC]---PORT MELBOURNE (VIC)",
    "L&H[SLS]---SPEC LIGHTING SOLUTIONS",
    "L&H[SLS]---SPEC LIGHTING SOLUTIONS",
    "L&H[SLS]---SPEC LIGHTING SOLUTIONS - (VIC)",
    "L&H---AIRPORT WEST (VIC)",
    "L&H---Albury {DLB} (NSW)",
    "L&H---ARARAT (VIC)",
    "L&H---BALLARAT (VIC)",
    "L&H---BAYSWATER {DLE}(VIC)",
    "L&H---BENDIGO (VIC)",
    "L&H---BULLEEN (VIC)",
    "L&H---CASTLEMAINE (VIC)",
    "L&H---COBURG (VIC)",
    "L&H---DANDENONG (VIC)",
    "L&H---DANDENONG {DLP} (VIC)",
    "L&H---EPPING {DFN} (VIC)",
    "L&H---ESIDIRECT (VIC)",
    "L&H---FRANKSTON {DLS} (VIC)",
    "L&H---GEELONG (VIC)",
    "L&H---HAMILTON (VIC)",
    "L&H---HOPPERS CROSSING (VIC)",
    "L&H---HOPPERS CROSSING PROJECTS (VIC)",
    "L&H---HORSHAM (VIC)",
    "L&H---LILYDALE (VIC)",
    "L&H---MOORABBIN (VIC)",
    "L&H---MORNINGTON (VIC)",
    "L&H---MORWELL (VIC)",
    "L&H---NUNAWADING (VIC)",
    "L&H---NUNAWADING {DMJ} (VIC)",
    "L&H---Pakenham {DNM} (VIC)",
    "L&H---PORTLAND (VIC)",
    "L&H---PRESTON (VIC)",
    "L&H---Projects (VIC)",
    "L&H---SALE {DMP} (VIC)",
    "L&H---SCORESBY (VIC)",
    "L&H---SHEPPARTON {DMR} (VIC)",
    "L&H---SOUTHBANK (VIC)",
    "L&H---STATE PROJECT DEPARTMENT (VIC)",
    "L&H---SUNSHINE (VIC)",
    "L&H---SUNSHINE WEST {DNA} (VIC)",
    "L&H---SWAN HILL (VIC)",
    "L&H---THOMASTOWN (VIC)",
    "L&H---TRARALGON {DMW} (VIC)",
    "L&H---VICTORIAN FULFILMENT CENTRE - (VIC)",
    "L&H---WANGARATTA {DMX} (VIC)",
    "L&H---WENDOUREE (VIC)",
    "L&H---WENDOUREE (VIC)",
    "L&H---Wodonga {DLI} (VIC)",
    "LECKY'S---ALBURY (NSW)",
    "LECKY'S---COBURG (VIC)",
    "LECKY'S---Collingwood (VIC)",
    "LECKY'S---DROMANA (VIC)",
    "LECKY'S---HALLAM (VIC)",
    "LECKY'S---Northcote (VIC)",
    "LECKY'S---Project Division",
    "LECKY'S---Sunbury (VIC)",
    "LECKY'S---SUNSHINE (VIC)",
    "LED Lighting Group",
    "LEDified Lighting Corporation Pty Ltd",
    "Lighting Wholesale and Design",
    "Lightique",
    "Lights Plus",
    "Mekolec Electrical & Data Supplies",
    "Melbourne Elevator & Lift Supplies",
    "MIDDYS---ABBOTSFORD (VIC)",
    "MIDDYS---AIRPORT WEST (VIC)",
    "MIDDYS---ALBURY (NSW)",
    "MIDDYS---BAIRNSDALE (VIC)",
    "MIDDYS---BALLARAT (VIC)",
    "MIDDYS---BALLARAT WEST (VIC)",
    "MIDDYS---BAYSWATER (VIC)",
    "MIDDYS---BENALLA (VIC)",
    "MIDDYS---BENDIGO (VIC)",
    "MIDDYS---BENDIGO NORTH (VIC)",
    "MIDDYS---BLACKBURN (VIC)",
    "MIDDYS---BRAESIDE (VIC)",
    "MIDDYS---BRUNSWICK (VIC)",
    "MIDDYS---BURWOOD (VIC)",
    "MIDDYS---CAMPBELLFIELD (VIC)",
    "MIDDYS---CARRUM DOWNS (VIC)",
    "MIDDYS---CHELTENHAM (VIC)",
    "MIDDYS---COLAC (VIC)",
    "MIDDYS---CRAIGIEBURN (VIC)",
    "MIDDYS---CRANBOURNE (VIC)",
    "MIDDYS---CRANBOURNE WEST (VIC)",
    "MIDDYS---DANDENONG (VIC)",
    "MIDDYS---DANDENONG SOUTH (VIC)",
    "MIDDYS---DENILIQUIN (NSW)",
    "MIDDYS---DROMANA (VIC)",
    "MIDDYS---ECHUCA (VIC)",
    "MIDDYS---ELTHAM (VIC)",
    "MIDDYS---ENERGY SMART",
    "MIDDYS---FRANKSTON (VIC)",
    "MIDDYS---GEELONG (VIC)",
    "MIDDYS---GEELONG NORTH (VIC)",
    "MIDDYS---GISBORNE (VIC)",
    "MIDDYS---GROVEDALE (VIC)",
    "MIDDYS---HABITAT LIVING",
    "MIDDYS---HALLAM (VIC)",
    "MIDDYS---HASTINGS (VIC)",
    "MIDDYS---Hawthorn (VIC)",
    "MIDDYS---HAWTHORN (VIC)",
    "MIDDYS---HEIDELBERG (VIC)",
    "MIDDYS---HOPPERS CROSSING (VIC)",
    "MIDDYS---HORSHAM (VIC)",
    "MIDDYS---KEILOR EAST (VIC)",
    "MIDDYS---LAVERTON (VIC)",
    "MIDDYS---LAVINGTON (NSW)",
    "MIDDYS---LEONGATHA (VIC)",
    "MIDDYS---LILYDALE (VIC)",
    "MIDDYS---MELBOURNE (VIC)",
    "MIDDYS---MELTON (VIC)",
    "MIDDYS---MERIMBULA (VIC)",
    "MIDDYS---MOORABBIN (VIC)",
    "MIDDYS---MORNINGTON (VIC)",
    "MIDDYS---MULGRAVE (VIC)",
    "MIDDYS---NARRE WARREN (VIC)",
    "MIDDYS---OAKLEIGH (VIC)",
    "MIDDYS---OCEAN GROVE (VIC)",
    "MIDDYS---PAKENHAM (VIC)",
    "MIDDYS---PRESTON (VIC)",
    "MIDDYS---RAVENHALL (VIC)",
    "MIDDYS---RINGWOOD (VIC)",
    "MIDDYS---ROSEBUD (VIC)",
    "MIDDYS---ROWVILLE (VIC)",
    "MIDDYS---SALE (VIC)",
    "MIDDYS---SEYMOUR (VIC)",
    "MIDDYS---SHEPPARTON (VIC)",
    "MIDDYS---SOUTH MORANG (VIC)",
    "MIDDYS---ST KILDA (VIC)",
    "MIDDYS---STAWELL (VIC)",
    "MIDDYS---SUNBURY (VIC)",
    "MIDDYS---SUNSHINE (VIC)",
    "MIDDYS---SWAN HILL (VIC)",
    "MIDDYS---THOMASTOWN (VIC)",
    "MIDDYS---TORQUAY (VIC)",
    "MIDDYS---TRARALGON (VIC)",
    "MIDDYS---WANGARATTA (VIC)",
    "MIDDYS---WARRAGUL (VIC)",
    "MIDDYS---Warrnambool (VIC)",
    "MIDDYS---WERRIBEE (VIC)",
    "MIDDYS---WHITTLESEA (VIC)",
    "MIDDYS---WILLIAMSTOWN (VIC)",
    "MIDDYS---WODONGA (VIC)",
    "MIDDYS---WONTHAGGI (VIC)",
    "MIDDYS---YARRAVILLE (VIC)",
    "MIDDYS---YARRAWONGA (VIC)",
    "Milestone Automation & Technology Pty Ltd",
    "MMEM[AWM]---ABBOTSFORD (VIC)",
    "MMEM[AWM]---AIRPORT WEST (VIC)",
    "MMEM[AWM]---ALBURY (NSW)",
    "MMEM[AWM]---ALTONA NORTH (VIC)",
    "MMEM[AWM]---BAIRNSDALE (VIC)",
    "MMEM[AWM]---BAYSWATER (VIC)",
    "MMEM[AWM]---BENDIGO (VIC)",
    "MMEM[AWM]---BRAESIDE (VIC)",
    "MMEM[AWM]---BRUNSWICK (VIC)",
    "MMEM[AWM]---BURWOOD (VIC)",
    "MMEM[AWM]---CAMPBELLFIELD (VIC)",
    "MMEM[AWM]---CARRUM DOWNS (VIC)",
    "MMEM[AWM]---CHELTENHAM (VIC)",
    "MMEM[AWM]---CLAYTON (VIC)",
    "MMEM[AWM]---COBRAM(VIC)",
    "MMEM[AWM]---COBURG NORTH (VIC)",
    "MMEM[AWM]---CRAIGIEBURN (VIC)",
    "MMEM[AWM]---CRANBOURNE (VIC)",
    "MMEM[AWM]---DANDENONG (VIC)",
    "MMEM[AWM]---DELACOMBE(VIC)",
    "MMEM[AWM]---DONCASTER (VIC)",
    "MMEM[AWM]---ECHUCA (VIC)",
    "MMEM[AWM]---ELTHAM (VIC)",
    "MMEM[AWM]---EPPING (VIC)",
    "MMEM[AWM]---FAIRFIELD (VIC)",
    "MMEM[AWM]---GEELONG (VIC)",
    "MMEM[AWM]---GROVEDALE (VIC)",
    "MMEM[AWM]---HAMILTON (VIC)",
    "MMEM[AWM]---HASTINGS (VIC)",
    "MMEM[AWM]---HEIDELBERG (VIC)",
    "MMEM[AWM]---HOPPERS CROSSING (VIC)",
    "MMEM[AWM]---KILSYTH (VIC)",
    "MMEM[AWM]---LILYDALE (VIC)",
    "MMEM[AWM]---MANSFIELD (VIC)",
    "MMEM[AWM]---MCKINNON (VIC)",
    "MMEM[AWM]---MELBOURNE (VIC)",
    "MMEM[AWM]---MELTON (VIC)",
    "MMEM[AWM]---MOOLAP (VIC)",
    "MMEM[AWM]---MOORABBIN (VIC)",
    "MMEM[AWM]---MORNINGTON (VIC)",
    "MMEM[AWM]---MORWELL (VIC)",
    "MMEM[AWM]---NARRE WARREN (VIC)",
    "MMEM[AWM]---NORTH GEELONG (VIC)",
    "MMEM[AWM]---NUNAWADING (VIC)",
    "MMEM[AWM]---OAKLEIGH (VIC)",
    "MMEM[AWM]---OCEAN GROVE (VIC)",
    "MMEM[AWM]---PAKENHAM (VIC)",
    "MMEM[AWM]---PORT MELBOURNE (VIC)",
    "MMEM[AWM]---RAVENHALL (VIC)",
    "MMEM[AWM]---REGION 2 HEAD OFFICE  (VIC)",
    "MMEM[AWM]---RINGWOOD (VIC)",
    "MMEM[AWM]---ROSEBUD (VIC)",
    "MMEM[AWM]---ROWVILLE (VIC)",
    "MMEM[AWM]---SALE (VIC)",
    "MMEM[AWM]---SCORESBY (VIC)",
    "MMEM[AWM]---SEAFORD (VIC)",
    "MMEM[AWM]---SHEPPARTON (VIC)",
    "MMEM[AWM]---SOUTH MELBOURNE (VIC)",
    "MMEM[AWM]---SOUTH MORANG (VIC)",
    "MMEM[AWM]---SUNBURY (VIC)",
    "MMEM[AWM]---SUNSHINE (VIC)",
    "MMEM[AWM]---THOMASTOWN (VIC)",
    "MMEM[AWM]---TRARALGON (VIC)",
    "MMEM[AWM]---TULLAMARINE (VIC)",
    "MMEM[AWM]---WARRNAMBOOL (VIC)",
    "MMEM[AWM]---WENDOUREE (VIC)",
    "MMEM[AWM]---WEST HEIDELBERG (VIC)",
    "MMEM[AWM]---WEST MELBOURNE (VIC)",
    "MMEM[AWM]---WHITE HILLS (VIC)",
    "MMEM[AWM]---WONTHAGGI (VIC)",
    "MMEM---SURREY HILLS (VIC)",
    "Q INDUSTRIES",
    "Radum Pty Ltd",
    "REXEL[IES]---CARNEGIE (VIC)",
    "REXEL[RES]---ALBURY (NSW)",
    "REXEL[RES]---WARRAGUL (VIC)",
    "REXEL---BENDIGO (VIC)",
    "REXEL---BRIAR HILL (VIC)",
    "REXEL---BROOKLYN (VIC)",
    "REXEL---DANDENONG (VIC)",
    "REXEL---FAIRFIELD (VIC)",
    "REXEL---KEILOR PARK (VIC)",
    "REXEL---KILSYTH (VIC)",
    "REXEL---KNOXFIELD(VIC)",
    "REXEL---MITCHAM (VIC)",
    "REXEL---MOORABBIN (VIC)",
    "REXEL---MOUNT WAVERLY (VIC)",
    "REXEL---NORTH GEELONG (VIC)",
    "REXEL---NUNAWADING (VIC)",
    "REXEL---RICHMOND (VIC)",
    "REXEL---SHEPPARTON (VIC)",
    "REXEL---THOMASTOWN (VIC)",
    "SHERRIFF---Melbourne (VIC)",
    "SHERRIFF---RAVENHALL (VIC)",
    "Shorelec Electrical Wholesalers - HEALESVILLE",
    "Shorelec Electrical Wholesalers - SAN REMO",
    "Site Supply Australia Pty Ltd",
    "TITAN TRADING---BRAESIDE",
    "TITAN TRADING---MULGRAVE",
    "TITAN TRADING---SPRINGVALE",
    "Tradezone Vic",
    "Vealls Electrical Wholesale",
    "Wilson Industries Pty Limited"
  ],
  NSW: [
    "8 Light",
    "Ablec Trading",
    "Access Lighting",
    "ACG Pty Ltd",
    "Action Electrical Supplies Pty Ltd",
    "Action Electrical Supplies Pty Ltd---BELFIELD (NSW)",
    "ADVANTAGE ELECTRICAL SUPPLIES",
    "AEW---Blue Mountains (NSW)",
    "AEW---Blue Mountains (NSW)",
    "AEW---Penrith (NSW)",
    "AEW---St Marys (NSW)",
    "AJ&PM SALES PTY LTD",
    "AJ&PM SALES PTY LTD---BEXLEY (NSW)",
    "AJ&PM SALES PTY LTD---FAIRY MEADOW (NSW)",
    "AJ&PM SALES PTY LTD---KIRRAWEE (NSW)",
    "AJ&PM SALES PTY LTD---SHOW ROOM (NSW)",
    "Alpha ESS Australia Pty Ltd",
    "Alstra Electrical Wholesalers",
    "Amore Lighting Pty Ltd",
    "Amore Lighting Pty Ltd",
    "Arc Renewable Group Pty Ltd",
    "Arc Renewable Group Pty Ltd",
    "Aussie Electrical Pty Ltd",
    "Austec Electrical Australia",
    "Australian Indigenous Electrical",
    "Avantic Constructions Pty Ltd",
    "AWE-SIM---GREGORY HILLS (NSW) FORMERLY MOOREBANK",
    "AWE-SIM---PENRITH (NSW)",
    "B&T Electrical Wholesalers Pty Ltd",
    "BGW SOLUTIONS",
    "Blackwoods Albury",
    "Blackwoods Dubbo",
    "Blackwoods Greystanes",
    "Blackwoods Newcastle",
    "Blackwoods Singleton",
    "Blackwoods Wollongong",
    "Blackwoods",
    "Boriantar Pty Ltd",
    "Bowral Electrical Wholesalers",
    "Buckley Bros Lawson",
    "Cash Sale NSW",
    "CASTLE HILL ELECTRICAL WHOLESALERS PTY LTD",
    "CASTLE HILL ELECTRICAL WHOLESALERS PTY LTD",
    "Castle Lighting Pty Ltd",
    "CDay Electrical Wholesalers",
    "Century Lighting Blacktown",
    "Century Lighting",
    "CES---CHATSWOOD (NSW)",
    "CES---EDGEWORTH (NSW)",
    "CES---MORISSET (NSW)",
    "CES---PRESTON (NSW)",
    "CES---SEVEN HILL (NSW)",
    "CES---SILVERWATER (NSW)",
    "CES---TAREN POINT (NSW)",
    "CES---TUGGERAH (NSW)",
    "CES---WEST GOSFORD (NSW)",
    "Cetnaj West Pty Ltd---ARMIDALE (NSW)",
    "Cetnaj West Pty Ltd---Cardiff (NSW)",
    "Cetnaj West Pty Ltd---Coffs Harbour (NSW)",
    "Cetnaj West Pty Ltd---COFFS HARBOUR (NSW)",
    "Cetnaj West Pty Ltd---DURAL (NSW)",
    "Cetnaj West Pty Ltd---EAST MAITLAND (NSW)",
    "Cetnaj West Pty Ltd---Erina (NSW)",
    "Cetnaj West Pty Ltd---ERINA (NSW)",
    "Cetnaj West Pty Ltd---Forster (NSW)",
    "Cetnaj West Pty Ltd---FORSTER (NSW)",
    "Cetnaj West Pty Ltd---Grafton (NSW)",
    "Cetnaj West Pty Ltd---GRAFTON (NSW)",
    "Cetnaj West Pty Ltd---Greenacre (NSW)",
    "Cetnaj West Pty Ltd---GUNNEDAH (NSW)",
    "Cetnaj West Pty Ltd---Hornsby (NSW)",
    "Cetnaj West Pty Ltd---HOXTON PARK (NSW) FORMERLY GO ELECTRICAL HOXTON PARK",
    "Cetnaj West Pty Ltd---KEMPSEY (NSW)",
    "Cetnaj West Pty Ltd---KEMPSEY (NSW)",
    "Cetnaj West Pty Ltd---Maitland (NSW)",
    "Cetnaj West Pty Ltd---MAITLAND (NSW)",
    "Cetnaj West Pty Ltd---MAYFIELD WEST (NSW)",
    "Cetnaj West Pty Ltd---MAYFIELD WEST (NSW)",
    "Cetnaj West Pty Ltd---Moree (NSW)",
    "Cetnaj West Pty Ltd---MUSWELLBROOK (NSW)",
    "Cetnaj West Pty Ltd---PRESTONS (NSW)",
    "Cetnaj West Pty Ltd---ROUSE HILL (NSW)",
    "Cetnaj West Pty Ltd---ROUSE HILL (NSW)",
    "Cetnaj West Pty Ltd---SILVERWATER (NSW)",
    "Cetnaj West Pty Ltd---SINGLETON (NSW)",
    "Cetnaj West Pty Ltd---SINGLETON (NSW)",
    "Cetnaj West Pty Ltd---Smeaton Grange (NSW)",
    "Cetnaj West Pty Ltd---TAMWORTH (NSW)",
    "Cetnaj West Pty Ltd---TAMWORTH (NSW)",
    "Cetnaj West Pty Ltd---TAREE (NSW)",
    "Cetnaj West Pty Ltd---TAREE (NSW)",
    "Cetnaj West Pty Ltd---WARNERS BAY (NSW)",
    "Cetnaj West Pty Ltd---WARNERS BAY (NSW)",
    "Cetnaj West Pty Ltd---WETHERILL PARK (NSW)",
    "CNW Pty Ltd---ALEXANDRIA (NSW)",
    "CNW Pty Ltd---BROADMEADOW (NSW)",
    "CNW Pty Ltd---CARDIFF (NSW)",
    "CNW Pty Ltd---CARINGBAH (NSW)",
    "CNW Pty Ltd---COFFS HARBOUR (NSW)",
    "CNW Pty Ltd---MAITLAND (NSW)",
    "CNW Pty Ltd---MORISSET (NSW)",
    "CNW Pty Ltd---ORANGE (NSW)",
    "CNW Pty Ltd---PORT MACQUARIE (NSW)",
    "CNW Pty Ltd---RUTHERFORD (NSW)",
    "CNW Pty Ltd---SEVEN HILLS (NSW)",
    "CNW Pty Ltd---SILVERWATER (NSW) FORMERLY AUBURN",
    "CNW Pty Ltd---SILVERWATER (NSW)",
    "CNW Pty Ltd---SMEATON GRANGE (NSW)",
    "CNW Pty Ltd---WARNERS BAY (NSW)",
    "CNW Pty Ltd---WOLLONGONG (NSW)",
    "Cobar Powerhouse---COBAR (NSW)",
    "COMPASS ELECTRICAL",
    "Concept Lighting",
    "Connect Civil & Electrical Supplies",
    "Cosmo Lighting",
    "Davis & Spence Pty Ltd---East Maitland (NSW)",
    "Davis & Spence Pty Ltd---Warners Bay (NSW)",
    "Davis & Spence Pty Ltd---Wickham (NSW)",
    "Deicorp Pty Ltd",
    "Direct Electrical Supplies",
    "Dubbo Powerhouse Pty Limited---DUBBO (NSW)",
    "Dubbo Powerhouse",
    "E&S Electrical Wholesalers Pty Ltd",
    "Edyco Group Pty Ltd",
    "Electrical Wholesalers Pty Ltd",
    "Electro Lighting",
    "Energy Electric Wholesale Pty Ltd",
    "Energy Electrical and Industrial Supplies Pty Ltd",
    "Energy Electrical Supplies",
    "ENVIROTECH1",
    "Ezlec Trade Supplies",
    "F & Co. Pty Ltd",
    "Fairfield Electrical Supplies---WETHERILL PARK (NSW)",
    "Fin Ballantines",
    "Focus Electrical Supplies",
    "Gainforts---HORNSBY (NSW)",
    "Gainforts---MONA VALE (NSW)",
    "GCM Lighting & Electrical---TAMWORTH (NSW)",
    "GCM Lighting, Electrical and Automotive---TAMWORTH (NSW)",
    "GEMROCK PTY LTD",
    "Globex Lighting",
    "Go Electrical---Alexandria (NSW)",
    "Go Electrical---Alexandria (NSW)",
    "Go Electrical---Artarmon (NSW) Special Projects",
    "Go Electrical---Artarmon (NSW)",
    "Go Electrical---Artarmon (NSW)",
    "Go Electrical---Belmont (NSW)",
    "Go Electrical---Belmont (NSW)",
    "Go Electrical---Caringbah (NSW)",
    "Go Electrical---Caringbah (NSW)",
    "Go Electrical---Castle Hill (NSW)",
    "Go Electrical---Castle Hill (NSW)",
    "Go Electrical---Charmhaven (NSW)",
    "Go Electrical---Charmhaven (NSW)",
    "Go Electrical---Hoxton Park (NSW)",
    "Go Electrical---Kincumber (NSW)",
    "Go Electrical---Kincumber (NSW)",
    "Go Electrical---Kirrawee (NSW)",
    "Go Electrical---Kirrawee (NSW)",
    "Go Electrical---Long Jetty (NSW)",
    "Go Electrical---Long Jetty (NSW)",
    "Go Electrical---Morisset (NSW)",
    "Go Electrical---Narellan (NSW)",
    "Go Electrical---Narellan (NSW)",
    "Go Electrical---Oak Flats (NSW)",
    "Go Electrical---Riverstone (NSW)",
    "Go Electrical---Roselands (NSW)",
    "Go Electrical---Roselands (NSW)",
    "Go Electrical---Silverwater (NSW)",
    "Go Electrical---Silverwater (NSW)",
    "Go Electrical---Sydney Sales Centre (NSW)",
    "Go Electrical---Thornleigh (NSW)",
    "Go Electrical---Thornleigh (NSW)",
    "Go Electrical---Tuggerah (NSW)",
    "Go Electrical---Tuggerah (NSW)",
    "Go Electrical---Wetherill Park (NSW)",
    "Go Electrical---Wetherill Park (NSW)",
    "GORDON MACDONALD---ALBION PARK (NSW)",
    "GORDON MACDONALD---BOWRAL (NSW)",
    "GORDON MACDONALD---NOWRA (NSW)",
    "GORDON MACDONALD---OAK FLATS (NSW)",
    "GORDON MACDONALD---Wollongong (NSW)",
    "GOULBURN ELECTRICAL",
    "Grange Electrical Suppliers",
    "Grange Electrical Suppliers",
    "Haneco Lighting Internal Use NSW",
    "Harvey Norman Commercial NSW/ACT",
    "HASTINGS ELECTRICAL PTY LTD",
    "HDJ Constructions",
    "Herkes Electrical Supplies---ROSEBERY (NSW)",
    "Hi-Light Australia Pty Ltd",
    "HJR Lighting",
    "JOHN R TURK---ALEXANDRIA (NSW)",
    "JOHN R TURK---ARTARMON (NSW)",
    "JOHN R TURK---BANKSTOWN (NSW)",
    "JOHN R TURK---BLACKTOWN (NSW)",
    "JOHN R TURK---BROOKVALE (NSW)",
    "JOHN R TURK---CAMPBELLTOWN (NSW)",
    "JOHN R TURK---CARINGBAH (NSW)",
    "JOHN R TURK---CASTLE HILL (NSW)",
    "JOHN R TURK---ERINA (NSW)",
    "JOHN R TURK---Gladesville (NSW)",
    "JOHN R TURK---GLENDENNING (NSW)",
    "JOHN R TURK---HOXTON PARK (NSW)",
    "JOHN R TURK---KINGSFORD (NSW)",
    "JOHN R TURK---LEICHHARDT (NSW)",
    "JOHN R TURK---PARRAMATTA (NSW)",
    "JOHN R TURK---Peakhurst (NSW)",
    "JOHN R TURK---PENRITH (NSW)",
    "JOHN R TURK---ROCKDALE (NSW)",
    "JOHN R TURK---SILVERWATER (NSW)",
    "JOHN R TURK---SYDNEY (NSW)",
    "JOHN R TURK---SYDNEY CITY (NSW)",
    "JOHN R TURK---SYDNEY CITY(NSW) NO REBATE ACCOUNT",
    "JOHN R TURK---THORNLEIGH (NSW)",
    "JOHN R TURK---VILLAWOOD (NSW)",
    "JOHN R TURK---WARNERVALE (NSW)",
    "JOHN R TURK---WETHERILL PARK (NSW)",
    "JOHN R TURK---WOLLONGONG (NSW)",
    "JOHN R TURK---WOLLONGONG (NSW)",
    "JOHN R TURK---WOY WOY (NSW)",
    "JOHN R TURK---WYONG (Tuggerah) (NSW)",
    "Kasta Technologies",
    "KETCH---TUGGERAH (NSW)",
    "Klassy Lighting",
    "Koala Lamps P/L",
    "KOALA LIGHTS---ULTIMO (NSW)",
    "L&H[AUSLEC]---BLACKTOWN (NSW)",
    "L&H[AUSLEC]---FORBES (NSW)",
    "L&H[AUSLEC]---FORBES (NSW)",
    "L&H[AUSLEC]---WETHERILL PARK (NSW)",
    "L&H[EWS]---BATHURST (NSW)",
    "L&H[EWS]---PARRAMATTA (NSW)",
    "L&H[EWS]---SYDNEY{DHD} (NSW)",
    "L&H[SLS]---SPEC LIGHTING SOLUTIONS - (NSW)",
    "L&H---ALEXANDRIA {DFA} (NSW)",
    "L&H---BANKSTOWN (NSW)",
    "L&H---BANKSTOWN (NSW)",
    "L&H---BATHURST (NSW)",
    "L&H---BATHURST (NSW)",
    "L&H---BLACKTOWN (NSW)",
    "L&H---BROOKVALE {DFG} (NSW)",
    "L&H---CAMPBELLTOWN {DFH} (NSW)",
    "L&H---CARDIFF (NSW)",
    "L&H---CASTLE HILL (NSW)",
    "L&H---COFFS HARBOUR (NSW)",
    "L&H---COFFS HARBOUR (NSW)",
    "L&H---DUBBO (NSW)",
    "L&H---GLADESVILLE (NSW)",
    "L&H---GOSFORD (NSW)",
    "L&H---GOSFORD (NSW)",
    "L&H---INVERELL (NSW)",
    "L&H---LANSVALE {DFW} (NSW)",
    "L&H---MUDGEE{DHP} (NSW)",
    "L&H---NEWCASTLE (NSW)",
    "L&H---NOWRA (NSW)",
    "L&H---NOWRA (NSW)",
    "L&H---ORANGE {DGG} (NSW)",
    "L&H---PAMBULA (NSW)",
    "L&H---PARKES (NSW)",
    "L&H---PENRITH (NSW)",
    "L&H---ROCKDALE {DHC} (NSW)",
    "L&H---SILVERWATER (NSW)",
    "L&H---STATE PRJ NSW (NSW)",
    "L&H---TAMWORTH{DGV} (NSW)",
    "L&H---TAREN POINT{DGA} (NSW)",
    "L&H---TIGHES HILL (NSW)",
    "L&H---TWEED HEADS (NSW)",
    "L&H---UNANDERRA (NSW)",
    "L&H---WAGGA WAGGA (NSW)",
    "L&H---WETHERILL PARK (NSW)",
    "L&H---WINDSOR (NSW)",
    "L&H---WOLLONGONG (NSW)",
    "L&H---YOUNG (NSW)",
    "LECKY'S HUNTER VALLEY ELECTRICAL WHOLESALERS",
    "Leichhardt Electrical Wholesalers Pty Ltd---LEICHHARDT (NSW)",
    "Light Up Kingsford",
    "Lighting & Living",
    "Lighting Mall",
    "Lights2you Pty Ltd",
    "Lumasign Pty Ltd",
    "Lumentec Lighting",
    "M&E Equipment Traders Pty Ltd",
    "Mases Lighting",
    "Mega Lighting",
    "MIDDYS (SBE) Pty Ltd",
    "MIDDYS [SBE]---ALEXANDRIA (NSW)",
    "MIDDYS [SBE]---FAIRFIELD (NSW)",
    "MIDDYS [SBE]---MEADOWBANK (NSW)",
    "MIDDYS [SBE]---NORTHMEAD (NSW)",
    "MIDDYS [SBE]---PADSTOW (NSW)",
    "Middys GEW",
    "MIDDYS---MINCHINBURY (NSW)",
    "MIDDYS---MOOREBANK (NSW)",
    "MIDDYS---PENRITH (NSW)",
    "MIDDYS---SMEATON GRANGE (NSW)",
    "MIDDYS---WAGGA WAGGA (NSW)",
    "MIDDYS---WAGGA WAGGA EAST (NSW)",
    "Minchinbury Lighting",
    "MMEM[BED]---BROOKVALE (NSW)",
    "MMEM[BED]---BROOKVALE ELECT (NSW)",
    "MMEM[DEFENCE]---RYDALMERE (NSW)",
    "MMEM[Greentech]---NEWCASTLE (NSW)",
    "MMEM[Greentech]---THORNLEIGH (NSW)",
    "MMEM[HAYMANS]---CARDIFF (NSW)",
    "MMEM[HAYMANS]---MAITLAND (NSW)",
    "MMEM[HAYMANS]---MOREE (NSW)",
    "MMEM[HAYMANS]---NARRABRI (NSW)",
    "MMEM[HAYMANS]---NEWCASTLE (NSW)",
    "MMEM[HAYMANS]---TAREE (NSW)",
    "MMEM[HAYMANS]---TWEED HEADS (NSW)",
    "MMEM[SEW]---DARLINGHURST (NSW)",
    "MMEM[SEW]---GLEBE (NSW)",
    "MMEM[SEW]---KINGSFORD (NSW)",
    "MMEM[TLE]---ALEXANDRIA (NSW)",
    "MMEM[TLE]---ARMIDALE (NSW)",
    "MMEM[TLE]---ARTARMON (NSW)",
    "MMEM[TLE]---BATEMANS BAY (NSW)",
    "MMEM[TLE]---BATHURST (NSW)",
    "MMEM[TLE]---BEGA (NSW)",
    "MMEM[TLE]---BLACKTOWN (NSW)",
    "MMEM[TLE]---BLUE MOUNTAINS (NSW) FORMERLY AEW Blue Mountains",
    "MMEM[TLE]---BROOKVALE (NSW)",
    "MMEM[TLE]---BURWOOD (NSW)",
    "MMEM[TLE]---CAMPBELLTOWN (NSW)",
    "MMEM[TLE]---CARINGBAH (NSW)",
    "MMEM[TLE]---CARLTON (NSW)",
    "MMEM[TLE]---CASTLE HILL (NSW)",
    "MMEM[TLE]---CHARMHAVEN (NSW)",
    "MMEM[TLE]---CHATSWOOD (NSW)",
    "MMEM[TLE]---COFFS HARBOUR (NSW)",
    "MMEM[TLE]---CONDELL PARK (NSW)",
    "MMEM[TLE]---COOMA (NSW)",
    "MMEM[TLE]---Cowra (NSW)",
    "MMEM[TLE]---DUBBO (NSW)",
    "MMEM[TLE]---DURAL (NSW)",
    "MMEM[TLE]---ERINA (NSW)",
    "MMEM[TLE]---Forbes (NSW)",
    "MMEM[TLE]---GATESHEAD (NSW)",
    "MMEM[TLE]---GLADESVILLE (NSW)",
    "MMEM[TLE]---Gosford (NSW)",
    "MMEM[TLE]---GOULBURN (NSW)",
    "MMEM[TLE]---GRAFTON (NSW)",
    "MMEM[TLE]---GRAFTON SOUTH (NSW)",
    "MMEM[TLE]---GRIFFITH (NSW)",
    "MMEM[TLE]---GUILDFORD (NSW)",
    "MMEM[TLE]---HORNSBY (NSW)",
    "MMEM[TLE]---HOXTON PARK (NSW)",
    "MMEM[TLE]---HOXTON PARK formerly LIVERPOOL",
    "MMEM[TLE]---INVERELL (NSW)",
    "MMEM[TLE]---JINDABYNE (NSW)",
    "MMEM[TLE]---LAKEMBA (NSW)",
    "MMEM[TLE]---LAKEMBA PROJECTS (NSW)",
    "MMEM[TLE]---LEETON (NSW)",
    "MMEM[TLE]---LEUMEAH (NSW)",
    "MMEM[TLE]---LITHGOW (NSW)",
    "MMEM[TLE]---LIVERPOOL (NSW) move to PRESTON",
    "MMEM[TLE]---MENAI (NSW)",
    "MMEM[TLE]---MINCHINBURY (NSW)",
    "MMEM[TLE]---MITTAGONG (NSW)",
    "MMEM[TLE]---MONA VALE (NSW)",
    "MMEM[TLE]---MOSMAN (NSW)",
    "MMEM[TLE]---MOSS VALE (NSW)",
    "MMEM[TLE]---MUDGEE (NSW)",
    "MMEM[TLE]---MUSWELLBROOK (NSW)",
    "MMEM[TLE]---NEWCASTLE (NSW)",
    "MMEM[TLE]---NOWRA (NSW)",
    "MMEM[TLE]---OAK FLATS (NSW)",
    "MMEM[TLE]---ORANGE (NSW)",
    "MMEM[TLE]---Parkes (NSW)",
    "MMEM[TLE]---PENRITH (NSW)",
    "MMEM[TLE]---PORT MACQUARIE (NSW)",
    "MMEM[TLE]---REGENTS PARK (NSW)",
    "MMEM[TLE]---ROSEBERY (NSW)",
    "MMEM[TLE]---RYDALMERE (NSW)",
    "MMEM[TLE]---SEVEN HILLS (NSW)",
    "MMEM[TLE]---SHELL HARBOUR (NSW)",
    "MMEM[TLE]---Silverwater (NSW)",
    "MMEM[TLE]---SMEATON GRANGE (NSW)",
    "MMEM[TLE]---ST LEONARDS (NSW)",
    "MMEM[TLE]---TAMWORTH (NSW)",
    "MMEM[TLE]---THORNLEIGH (NSW)",
    "MMEM[TLE]---ULLADULLA (NSW)",
    "MMEM[TLE]---WAGGA (NSW)",
    "MMEM[TLE]---WAGGA WAGGA (NSW)",
    "MMEM[TLE]---WARABROOK (NSW)",
    "MMEM[TLE]---WARILLA (NSW)",
    "MMEM[TLE]---WETHERILL PARK (NSW)",
    "MMEM[TLE]---WINDSOR (NSW)",
    "MMEM[TLE]---Wollongong (NSW)",
    "MMEM[TLE]---YAMBA (NSW)",
    "MMEM---BERESFIELD (NSW)",
    "MMEM---NEWCASTLE (NSW)",
    "MMEM---NORTH ROCKS (NSW)",
    "MMEM---PRESTONS (NSW) (FORMERLY CETNAJ)",
    "MMEM---SMEATON GRANGE (NSW)",
    "MMEM---WETHERILL PARK (NSW)",
    "Muswellbrook Electrical Supplies",
    "Network Electrical Supplies",
    "Nordwest Lighting Pty Ltd",
    "Northern Lighting",
    "Opal Electrical Supplies Pty Ltd",
    "Opal Lighting Systems",
    "OPTIMISE ENERGY SOLUTIONS[OES]---SYDNEY (NSW) FORMERLY KNOWN AS FUTURE ENERGY",
    "Paul's Lighting",
    "PDC---SILVERWATER (NSW)",
    "PEW Prospect Electrical Wholesalers Pty Ltd",
    "PEW---BLACKTOWN (NSW)",
    "PEW---KINGS PARK (NSW)",
    "PowerPlus Lighting & Electrical Supp Griffith P/L---GRIFFITH (NSW)",
    "PowerPlus Lighting & Electrical Supp Griffith P/L---LEETON (NSW)",
    "PowerPlus Lighting & Electrical Supplies P/L---WAGGA WAGGA (NSW)",
    "POWERPLUS---WAGGA (NSW)",
    "PROJECT LIGHTING PTY LTD---BATEMANS BAY(NSW)",
    "PROJECT LIGHTING PTY LTD---ORANGE(NSW)",
    "PROJECT LIGHTING PTY LTD---ULLADULLA (NSW)",
    "Pulvin Composite Pty Ltd",
    "PULVIN LIGHTING PTY LTD (NSW Michelle)",
    "Q Automation Pty Ltd",
    "REXEL[IES]---TWEED HEADS (NSW)",
    "REXEL[IES]---TWEED HEADS (NSW)",
    "REXEL[INDUSTRIAL]---WOLLONGONG (NSW)",
    "REXEL[JRT]---PEAKHURST (NSW)",
    "REXEL[LEAR&SMITH]---CESSNOCK (NSW)",
    "REXEL[LEAR&SMITH]---GUNNEDAH (NSW)",
    "REXEL[LEAR&SMITH]---LAMBTON (NSW)",
    "REXEL[LEAR&SMITH]---PORT MACQUARIE (NSW)",
    "REXEL[LEAR&SMITH]---RAYMOND TERRACE (NSW)",
    "REXEL[LEAR&SMITH]---SINGLETON (NSW)",
    "REXEL[LEAR&SMITH]---Taree (NSW)",
    "REXEL[LEAR&SMITH]---TAREE (NSW)",
    "REXEL[LEAR&SMITH]---TAYLORS BEACH (NSW)",
    "REXEL[RES]---ALEXANDRIA (NSW)",
    "REXEL[RES]---Bathurst (NSW)",
    "REXEL[RES]---Blacktown (NSW)",
    "REXEL[RES]---Dubbo (NSW)",
    "REXEL[RES]---GLENDENNING (NSW)",
    "REXEL[RES]---Wagga Wagga (NSW)",
    "REXEL[RES]---Wollongong (NSW)",
    "REXEL[RES]---Young (NSW)",
    "REXEL[RIA]---SYDNEY (NSW)",
    "REXEL---Alexandria (NSW)",
    "REXEL---BLACKTOWN (NSW)",
    "REXEL---CASTLE HILL (NSW)",
    "REXEL---SURRY HILLS (NSW)",
    "REXEL---WAGGA WAGGA (NSW)",
    "REXEL---WOLLONGONG (NSW)",
    "REXEL---WYONG (NSW)",
    "REXEL---YOUNG (NSW)",
    "RITERA ELECTRICAL",
    "RITERA ELECTRICAL---ALEXANDRIA (NSW)",
    "RITERA ELECTRICAL---GLADESVILLE (NSW)",
    "RITERA ELECTRICAL---ROSEBERY (NSW)",
    "Rovert Lighting & Electrical",
    "Rovert Lighting & Electrical---BROADMEADOW (NSW)",
    "Rovert Lighting & Electrical---PORT MACQUARIE (NSW)",
    "Rovert Lighting & Electrical---TORONTO (NSW)",
    "RSH Electrical Distributors",
    "Salmon---AXANDRIA (NSW)",
    "Salmon---FRFIELD (NSW)",
    "Salmon---MDOWBANK (NSW)",
    "Salmon---NTHMEAD (NSW)",
    "Salmon---PDSTOW (NSW)",
    "Salmon---SRY HILLS (NSW)",
    "Schnap Electric Products",
    "SDA Electrical",
    "SE Distribution",
    "Shannon Electrics",
    "Super Cheap Electrical",
    "SWITCHED ON ELECTRICAL SUPPLIES",
    "Sydney Residential Lighting",
    "T Plus Smart Solutions Pty Ltd",
    "T1 Constructions Pty Ltd",
    "T1 Constructions Pty Ltd",
    "The Electrical Guys Pty Ltd - Prestons",
    "The Electrical Guys Pty Ltd - Seven Hills",
    "The Electrical Guys Pty Ltd",
    "The Grand Villa Furnishings (E&S)",
    "The Lighting Outlet",
    "TLI Lighting Technology",
    "TNY LED Pty Ltd",
    "TRADE ELECTRICAL DATA SUPPLIES",
    "Tradezone NSW",
    "Turnkey Innovative Engineering",
    "United Electrical Supplies Pty Ltd",
    "Voltage Wholesale Pty Ltd",
    "VOLTEX ELECTRICAL ACCESSORIES {CABLE-LOC}",
    "Zoltan Electrical & Plumbing"

  ],
  QLD: [
    "ALLPOWER ELECTRICAL WHOLESALERS PTY LTD",
    "Alpha LED Lighting",
    "Austep Eco Pty Ltd",
    "Blackwoods Cairns",
    "Blackwoods Carole Park",
    "Blackwoods Mackay",
    "Blackwoods Mount Isa",
    "Blackwoods Rockhampton",
    "CAIRNS ELECTRICAL WHOLESALERS",
    "CAIRNS ELECTRICAL WHOLESALERS",
    "Cash Sale QLD",
    "Cetnaj Infrastructure (CIS)---BRENDALE (QLD)",
    "Cetnaj West Pty Ltd---ALBION (QLD)",
    "Cetnaj West Pty Ltd---ALBION (QLD)",
    "Cetnaj West Pty Ltd---ASHMORE (QLD)",
    "Cetnaj West Pty Ltd---ASHMORE (QLD)",
    "Cetnaj West Pty Ltd---BALLINA (NSW)",
    "Cetnaj West Pty Ltd---BALLINA (NSW)",
    "Cetnaj West Pty Ltd---BEENLEIGH (QLD)",
    "Cetnaj West Pty Ltd---BEENLEIGH (QLD)",
    "Cetnaj West Pty Ltd---BRENDALE (QLD)",
    "Cetnaj West Pty Ltd---BRENDALE (QLD)",
    "Cetnaj West Pty Ltd---BURLEIGH HEADS (QLD)",
    "Cetnaj West Pty Ltd---BURLEIGH HEADS (QLD)",
    "Cetnaj West Pty Ltd---CAPALABA (QLD)",
    "Cetnaj West Pty Ltd---CAPALABA (QLD)",
    "Cetnaj West Pty Ltd---CRESTMEAD (QLD)",
    "Cetnaj West Pty Ltd---ENOGGERA (QLD)",
    "Cetnaj West Pty Ltd---ENOGGERA (QLD)",
    "Cetnaj West Pty Ltd---GEEBUNG (QLD)",
    "Cetnaj West Pty Ltd---GEEBUNG (QLD)",
    "Cetnaj West Pty Ltd---IPSWICH (QLD)",
    "Cetnaj West Pty Ltd---Lismore (NSW)",
    "Cetnaj West Pty Ltd---LISMORE (NSW)",
    "Cetnaj West Pty Ltd---MAROOCHYDORE (QLD)",
    "Cetnaj West Pty Ltd---MURARRIE (QLD)",
    "Cetnaj West Pty Ltd---MURARRIE (QLD)",
    "Cetnaj West Pty Ltd---NOOSA (QLD)",
    "Cetnaj West Pty Ltd---REDCLIFFE (QLD)",
    "Cetnaj West Pty Ltd---REDCLIFFE (QLD)",
    "Cetnaj West Pty Ltd---REDLAND BAY (QLD)",
    "Cetnaj West Pty Ltd---SALISBURY (QLD)",
    "Cetnaj West Pty Ltd---SALISBURY (QLD)",
    "Cetnaj West Pty Ltd---SLACKS CREEK (QLD)",
    "Cetnaj West Pty Ltd---SLACKS CREEK (QLD)",
    "Cetnaj West Pty Ltd---TWEED HEADS (NSW)",
    "Cetnaj West Pty Ltd---TWEED HEADS (NSW)",
    "Cetnaj West Pty Ltd---WARANA (QLD)",
    "Cetnaj West Pty Ltd---WEST IPSWICH (QLD)",
    "CNW Pty Ltd---ARCHERFIELD (QLD)",
    "CNW Pty Ltd---Ballina (NSW)",
    "CNW Pty Ltd---BOWEN HILLS (QLD)",
    "CNW Pty Ltd---BRISBANE (QLD)",
    "CNW Pty Ltd---BURLEIGH (QLD)",
    "CNW Pty Ltd---BYRON BAY (NSW)",
    "CNW Pty Ltd---CABOOLTURE (QLD)",
    "CNW Pty Ltd---CHINCHILLA (QLD)",
    "CNW Pty Ltd---DISTRIBUTION (QLD)",
    "CNW Pty Ltd---EMERALD (QLD)",
    "CNW Pty Ltd---ENOGGERA (QLD)",
    "CNW Pty Ltd---GEEBUNG (QLD)",
    "CNW Pty Ltd---HENDRA (QLD)",
    "CNW Pty Ltd---HERVEY BAY (QLD)",
    "CNW Pty Ltd---IPSWICH (QLD)",
    "CNW Pty Ltd---IT SUPPORT (QLD)",
    "CNW Pty Ltd---Kunda Park (QLD)",
    "CNW Pty Ltd---MARYBOROUGH (QLD)",
    "CNW Pty Ltd---MOUNT ISA (QLD)",
    "CNW Pty Ltd---MURARRIE (QLD)",
    "CNW Pty Ltd---NERANG (QLD)",
    "CNW Pty Ltd---OXENFORD (QLD)",
    "CNW Pty Ltd---PINKENBA (QLD)",
    "CNW Pty Ltd---ROCKHAMPTON (QLD)",
    "CNW Pty Ltd---ROCKLEA (QLD)",
    "CNW Pty Ltd---SEQ PROJECT LIGHTING (QLD)",
    "CNW Pty Ltd---SLACKS CREEK (QLD)",
    "CNW Pty Ltd---SOUTHPORT (QLD)",
    "CNW Pty Ltd---TOOWOOMBA (QLD)",
    "CNW Pty Ltd---WARANA (QLD)",
    "Electrotek QLD Pty Ltd",
    "Expro Qld Pty Ltd",
    "First Stop Electrical Wholesale",
    "Go Electrical---Albion (QLD)",
    "Go Electrical---Albion (QLD)",
    "Go Electrical---BROWNS PLAINS (QLD)",
    "Go Electrical---BROWNS PLAINS (QLD)",
    "Go Electrical---Caloundra (QLD)",
    "Go Electrical---Capalaba (QLD)",
    "Go Electrical---Capalaba (QLD)",
    "Go Electrical---Geebung (QLD)",
    "Go Electrical---Hillcrest (QLD)",
    "Go Electrical---Salisbury (QLD)",
    "Go Electrical---Salisbury (QLD)",
    "Go Electrical---Warana (QLD)",
    "Haneco Lighting Internal Use QLD",
    "INTERLEC---BANYO (QLD)",
    "INTERLEC---BRENDALE (QLD)",
    "INTERLEC---CAIRNS (QLD)",
    "JOHN R TURK---COOPERS PLAINS (QLD)",
    "JOHN R TURK---ENOGGERA(QLD)",
    "JOHN R TURK---GEEBUNG (QLD)",
    "JOHN R TURK---MAYNE (QLD)",
    "JOHN R TURK---STRATHPINE (QLD)",
    "JOHN R TURK---WACOL (QLD)",
    "Ketch Industries Pty Ltd",
    "KOALA LIGHTS---ALBION (QLD)",
    "L&H[AUSLEC]---BILOELA (QLD)",
    "L&H[AUSLEC]---GEEBUNG (QLD)",
    "L&H[AUSLEC]---SALISBURY (QLD)",
    "L&H[AUSLEC]---TOOWOOMBA (QLD)",
    "L&H[PDC]---MURARRIE (QLD)",
    "L&H---BALLINA (NSW)",
    "L&H---BOWEN {DCD} (QLD)",
    "L&H---BROWNS PLAINS {DAD} (QLD)",
    "L&H---BUNDABERG (QLD)",
    "L&H---BURLEIGH WATERS {DBO} (QLD)",
    "L&H---CABOOLTURE{DAF} (QLD)",
    "L&H---CAPALABA {DAJ} (QLD)",
    "L&H---CHINCHILLA (QLD)",
    "L&H---COORPAROO {DAL} (QLD)",
    "L&H---EPC SUPPLY (QLD)",
    "L&H---HERVEY BAY (QLD)",
    "L&H---LAWNTON (QLD)",
    "L&H---LISMORE {DAX} (NSW)",
    "L&H---MAROOCHYDORE{DAZ} (QLD)",
    "L&H---MARYBOROUGH (QLD)",
    "L&H---MORANBAH {DCG} (QLD)",
    "L&H---NAMBOUR {DBB} (QLD)",
    "L&H---NERANG (QLD)",
    "L&H---NEWSTEAD {DAP} (QLD)",
    "L&H---NOOSA {DBD} (QLD)",
    "L&H---QUEENSLAND FULFILMENT CENTRE - (QLD)",
    "L&H---SLACKS CREEK {DBJ} (QLD)",
    "L&H---SUMNER PARK (QLD)",
    "L&H---SURFERS PARADISE (QLD)",
    "L&H---TINGALPA (QLD)",
    "L&H---TOOWOOMBA (QLD)",
    "LED-Now",
    "Life LED Lighting",
    "Lighting Illusions",
    "Linear Lux",
    "LUMEN-8 ARCHITECTURAL LIGHTING",
    "MIDDYS---BRENDALE (QLD)",
    "MIDDYS---MEADOWBROOK (QLD)",
    "MIDDYS---NERANG (QLD)",
    "MIDDYS---TINGALPA (QLD)",
    "MIDDYS---VIRGINIA (QLD)",
    "MMEM[Greentech]---Airport (QLD)",
    "MMEM[Greentech]---Burleigh (QLD)",
    "MMEM[HAYMANS]---AIRLIE BEACH (QLD)",
    "MMEM[HAYMANS]---AIRLIE BEACH (QLD)",
    "MMEM[HAYMANS]---Airport (QLD)",
    "MMEM[HAYMANS]---Airport Industrial & Infrastructure (QLD)",
    "MMEM[HAYMANS]---ARCHERFIELD (QLD)",
    "MMEM[HAYMANS]---ATHERTON (QLD)",
    "MMEM[HAYMANS]---BALLINA (NSW)",
    "MMEM[HAYMANS]---BALLINA (NSW)",
    "MMEM[HAYMANS]---Beaudesert (QLD)",
    "MMEM[HAYMANS]---BEERWAH (QLD)",
    "MMEM[HAYMANS]---BOWEN (QLD)",
    "MMEM[HAYMANS]---BRENDALE (QLD)",
    "MMEM[HAYMANS]---BROWNS PLAINS (QLD)",
    "MMEM[HAYMANS]---BUNDABERG (QLD)",
    "MMEM[HAYMANS]---BUNDALL (QLD)",
    "MMEM[HAYMANS]---BURLEIGH HEADS (QLD)",
    "MMEM[HAYMANS]---BYRON BAY (NSW)",
    "MMEM[HAYMANS]---CALOUNDRA (QLD)",
    "MMEM[HAYMANS]---CAPALABA (QLD)",
    "MMEM[HAYMANS]---Chinchilla (QLD)",
    "MMEM[HAYMANS]---CURRUMBIN (QLD)",
    "MMEM[HAYMANS]---DALBY (QLD)",
    "MMEM[HAYMANS]---Edmonton (QLD)",
    "MMEM[HAYMANS]---EMERALD (QLD)",
    "MMEM[HAYMANS]---FAIRFIELD (QLD)",
    "MMEM[HAYMANS]---FORTITUDE VALLEY (QLD)",
    "MMEM[HAYMANS]---GATTON (QLD)",
    "MMEM[HAYMANS]---GYMPIE (QLD)",
    "MMEM[HAYMANS]---HERVEY BAY (QLD)",
    "MMEM[HAYMANS]---INGHAM (QLD)",
    "MMEM[HAYMANS]---Innisfail (QLD)",
    "MMEM[HAYMANS]---IPSWICH (QLD)",
    "MMEM[HAYMANS]---KINGAROY (QLD)",
    "MMEM[HAYMANS]---KIRWAN (QLD)",
    "MMEM[HAYMANS]---LISMORE (NSW)",
    "MMEM[HAYMANS]---MANSFIELD (QLD)",
    "MMEM[HAYMANS]---MAROOCHYDORE (QLD)",
    "MMEM[HAYMANS]---MARYBOROUGH (QLD)",
    "MMEM[HAYMANS]---MILTON (QLD)",
    "MMEM[HAYMANS]---MORAYFIELD (QLD)",
    "MMEM[HAYMANS]---MOUNT ISA (QLD)",
    "MMEM[HAYMANS]---NAMBOUR (QLD)",
    "MMEM[HAYMANS]---NOOSA (QLD)",
    "MMEM[HAYMANS]---OXENFORD (QLD)",
    "MMEM[HAYMANS]---ROMA (QLD)",
    "MMEM[HAYMANS]---ROTHWELL (QLD)",
    "MMEM[HAYMANS]---SLACKS CREEK (QLD)",
    "MMEM[HAYMANS]---SLACKS CREEK (QLD)",
    "MMEM[HAYMANS]---SMITHFIELD (QLD)",
    "MMEM[HAYMANS]---Stafford (QLD)",
    "MMEM[HAYMANS]---SUMNER PARK (QLD)",
    "MMEM[HAYMANS]---SURFERS PARADISE (QLD)",
    "MMEM[HAYMANS]---TINGALPA (QLD)",
    "MMEM[HAYMANS]---Toowoomba (QLD)",
    "MMEM[HAYMANS]---TOWNSVILLE (QLD)",
    "MMEM[HAYMANS]---Virginia (QLD)",
    "MMEM[HAYMANS]---WARANA (QLD)",
    "MMEM[HAYMANS]---Warwick (QLD)",
    "MMEM[HAYMANS]---YATALA (QLD)",
    "MMEM[HAYMANS]---YEPPOON (QLD)",
    "MMEM---ALBION (QLD)",
    "MMEM---COOLUM (QLD)",
    "MMEM---MAROOCHYDORE (QLD)",
    "MMEM---REDLAND BAY (QLD)",
    "MMEM---ROCKHAMPTON (QLD)",
    "MMEM---SALISBURY (QLD)",
    "MMEM---TOOWOOMBA (QLD)",
    "MMEM---TOWNSVILLE (QLD)",
    "MMEM---VARSITY LAKES (QLD)",
    "MMEM---WAKERLEY (QLD)",
    "Overseas Distributors & General Trade Supplies",
    "Procureit Australia Prt Ltd",
    "Pro-Lamps Pty Ltd",
    "REXEL[IES]---ASPLEY (QLD)",
    "REXEL[IES]---BIGGERA WATERS (QLD)",
    "REXEL[IES]---BOKARINA (QLD)",
    "REXEL[IES]---BUNDABERG (QLD)",
    "REXEL[IES]---BURLEIGH (QLD)",
    "REXEL[IES]---CAIRNS (QLD)",
    "REXEL[IES]---CAPALABA (QLD)",
    "REXEL[IES]---CURRUMBIN (QLD)",
    "REXEL[IES]---EAGLE FARM (QLD)",
    "REXEL[IES]---EAST BRISBANE (QLD)",
    "REXEL[IES]---EDMONTON (QLD)",
    "REXEL[IES]---ENOGGERA (QLD)",
    "REXEL[IES]---GYMPIE (QLD)",
    "REXEL[IES]---IPSWICH (QLD)",
    "REXEL[IES]---MACKAY (QLD)",
    "REXEL[IES]---MAROOCHYDORE (QLD)",
    "REXEL[IES]---MILTON (QLD)",
    "REXEL[IES]---MORAYFIELD (QLD)",
    "REXEL[IES]---NERANG (QLD)",
    "REXEL[IES]---NORTH LAKES (QLD)",
    "REXEL[IES]---NORTH ROCKHAMPTON (QLD)",
    "REXEL[IES]---OXENFORD (QLD)",
    "REXEL[IES]---SALISBURY (QLD)",
    "REXEL[IES]---SLACKS CREEK (QLD)",
    "REXEL[IES]---SURFERS PARADISE (QLD) NO REBATE ACCOUNT",
    "REXEL[IES]---SURFERS PARADISE (QLD)",
    "REXEL[IES]---TOOWOOMBA (QLD)",
    "REXEL[IES]---UNDERWOOD (QLD)",
    "REXEL[IES]---UPPER MOUNT GRAVATT (QLD)",
    "REXEL[IES]---WYNNUM (QLD)",
    "REXEL---ACACIA RIDGE (QLD)",
    "REXEL---CAIRNS (QLD)",
    "REXEL---CALOUNDRA (QLD)",
    "REXEL---MAROOCHYDORE (QLD)",
    "REXEL---NAMBOUR(QLD)",
    "REXEL---NERANG (QLD)",
    "REXEL---ROCKHAMPTON (QLD)",
    "REXEL---ROMA (QLD)",
    "REXEL---SUMNER PARK (QLD)",
    "REXEL---TINGALPA (QLD)",
    "REXEL---TOWNSVILLE (QLD)",
    "REXEL---WARWICK (QLD)",
    "REXEL---YATALA (QLD)",
    "SHERRIFF---ALBION (QLD)",
    "SHERRIFF---BUNDABERG (QLD)",
    "SHERRIFF---CLONCURRY (QLD)",
    "SHERRIFF---GYMPIE (QLD)",
    "SHERRIFF---IPSWICH (QLD)",
    "SHERRIFF---MAROOCHYDORE (QLD)",
    "SHERRIFF---TOOWOOMBA (QLD)",
    "SHERRIFF---WACOL (QLD)",
    "SOUTH PACIFIC OFFSHORE ELECTRICAL & ENGINEERING CO PTY LTD",
    "Storage King Southport",
    "The Light House Noosa",
    "THE LIGHT HOUSE-----TOOWOOMBA (QLD)",
    "Tradezone Pty Ltd",
    "Tradezone Qld - Brisbane",
    "Tradezone Qld - Helensvale",
    "Warranty"

  ],
  WA: [
    "Advanced Electrical Equipment Pty Ltd",
    "AEE---BROOME (WA)",
    "AEE---BUNBURY (WA)",
    "AEE---GERALDTON (WA)",
    "AEE---JOONDALUP (WA)",
    "AEE---MALAGA (WA)",
    "AEE---O'CONNOR (WA)",
    "AEE---OSBORNE PARK (WA)",
    "AEE---WELSHPOOL (WA)",
    "Blackwoods Broome",
    "Blackwoods Bunbury",
    "Blackwoods Canning Vale DC",
    "Blackwoods Karratha",
    "Blackwoods Kwinana",
    "Blackwoods Port Hedland",
    "Boss Illumination Australia",
    "Cash Sale WA",
    "CES---BALCATTA (WA)",
    "CES---BIBRA LAKE (WA)",
    "CES---BUNBURY (WA)",
    "CES---CITY WEST (WA)",
    "CES---CLARKSON (WA)",
    "CES---MANDURAH (WA)",
    "CES---MIDLAND (WA)",
    "CES---PORT KENNEDY (WA)",
    "CES---WANGARA (WA)",
    "CES---WELSHPOOL (WA)",
    "CNW Energy Pty Ltd---KARRATHA (WA)",
    "CNW Pty Ltd---BALCATTA (WA)",
    "CNW Pty Ltd---BIBRA LAKE (WA)",
    "CNW Pty Ltd---BUNBURY (WA)",
    "CNW Pty Ltd---GERALDTON (WA)",
    "CNW Pty Ltd---HENDERSON (WA)",
    "CNW Pty Ltd---KARRATHA (WA)",
    "CNW Pty Ltd---MADDINGTON (WA)",
    "CNW Pty Ltd---MALAGA (WA)",
    "CNW Pty Ltd---MYAREE (WA)",
    "CNW Pty Ltd---OSBORNE PARK (WA)",
    "CNW Pty Ltd---PORT HEDLAND (WA)",
    "CNW Pty Ltd---REDCLIFFE (WA)",
    "CNW Pty Ltd---WANGARA (WA)",
    "ED---BALCATTA (WA)",
    "ED---BELMONT (WA)",
    "ED---BENTLEY (WA)",
    "ED---BOORAGOON (WA)",
    "ED---BUSSELTON (WA)",
    "ED---COCKBURN CENTRAL (WA)",
    "ED---KELMSCOTT (WA)",
    "ED---LANDSDALE (WA)",
    "ED---MANDURAH (WA)",
    "ED---NAVAL BASE (WA)",
    "ED---NEWMAN (WA)",
    "ESS---Kewdale (WA)",
    "Haneco Lighting Internal Use WA",
    "L&H[AUSLEC]---BALCATTA (WA)",
    "L&H[AUSLEC]---BUNBURY (WA)",
    "L&H[AUSLEC]---GERALDTON (WA)",
    "L&H[AUSLEC]---KALGOORLIE (WA)",
    "L&H[AUSLEC]---KARRATHA {DUP} (WA)",
    "L&H[AUSLEC]---PORT HEDLAND (WA)",
    "L&H[PDC]---BELMONT (WA)",
    "L&H[WILLIAMS]---BALCATTA {DVH} (WA)",
    "L&H---BALCATTA (WA)",
    "L&H---BELMONT (WA) [DVD]",
    "L&H---BUNBURY (WA)",
    "L&H---BUSSELTON (WA)",
    "L&H---CANNING VALE (WA)",
    "L&H---EMBLETON (WA)",
    "L&H---JOONDALUP (WA)",
    "L&H---KELMSCOTT (WA)",
    "L&H---MALAGA (WA)",
    "L&H---MANDURAH {DUT} (WA)",
    "L&H---MARGARET RIVER (WA)",
    "L&H---MIDLAND (WA)",
    "L&H---MIDLAND (WA)",
    "L&H---MIDVALE (WA)",
    "L&H---MINING (WELSHPOOL) (WA)",
    "L&H---MYAREE {DUW} (WA)",
    "L&H---OSBORNE PARK (WA)",
    "L&H---PROJECTS (WELSHPOOL) (WA)",
    "L&H---Rockingham (WA)",
    "L&H---WA RDC (WA)",
    "L&H---WANGARA {DVB} (WA)",
    "L&H---WANNEROO (WA)",
    "L&H---WELSHPOOL (WA){DVP}",
    "Lamp Replacements",
    "Lamparts WA",
    "LED Esperance",
    "LED Goldfields",
    "LED Perth",
    "MIDDYS---BALCATTA (WA)",
    "MIDDYS---BIBRA LAKE (WA)",
    "MIDDYS---EMBLETON (WA)",
    "MIDDYS---MUNDARING (WA)",
    "MIDDYS---WANGARA (WA)",
    "MIDDYS---WELSHPOOL (WA)",
    "MIW Electrical Wholesalers Bibra Lake",
    "MIW Electrical Wholesalers Busselton",
    "MIW Electrical Wholesalers Malaga",
    "MIW Electrical Wholesalers Osborne Park",
    "MIW Electrical Wholesalers Welshpool",
    "MMEM[D&W]---BASSENDEAN (WA)",
    "MMEM[D&W]---O'CONNOR (WA)",
    "MMEM[Greentech]---BASSENDEAN (WA)",
    "MMEM[Greentech]---BASSENDEAN (WA)",
    "MMEM---ALBANY (WA)",
    "MMEM---ARMADALE (WA)",
    "MMEM---BALCATTA (WA)",
    "MMEM---BIBRA LAKE (WA)",
    "MMEM---Bunbury (WA)",
    "MMEM---BUSSELTON (WA)",
    "MMEM---CANNING VALE (WA)",
    "MMEM---CLARKSON (WA)",
    "MMEM---GERALDTON (WA)",
    "MMEM---JANDAKOT (WA)",
    "MMEM---JOONDALUP (WA)",
    "MMEM---KALGOORLIE (WA)",
    "MMEM---KARRATHA (WA)",
    "MMEM---MALAGA (WA)",
    "MMEM---MANDURAH (WA)",
    "MMEM---MIDLAND (WA)",
    "MMEM---MIDLAND (WA)",
    "MMEM---NORTHAM (WA)",
    "MMEM---Northbridge (WA)",
    "MMEM---O'Connor RW1 (WA)",
    "MMEM---Osborne Park (WA)",
    "MMEM---ROCKINGHAM (WA)",
    "MMEM---WANGARA (WA)",
    "MMEM---WELSHPOOL (WA)",
    "MYELEC MINING---CANNING VALE (WA)",
    "MYELEC MINING---WELSHPOOL (WA)",
    "MYELEC PROJECTS---CANNING VALE (WA)",
    "MYELEC PROJECTS---WELSHPOOL (WA)",
    "MYELEC SOLAR---CANNING VALE (WA)",
    "MYELEC[Starclip]---Bibra Lake (WA) Formerly O'Connor",
    "MYELEC[Starclip]---BIBRA LAKE (WA)",
    "MYELEC[Starclip]---CANNING VALE (WA)",
    "MYELEC[Starclip]---COCKBURN (WA)",
    "MYELEC[Starclip]---JOONDALUP (WA)",
    "MYELEC[Starclip]---MALAGA (WA)",
    "MYELEC[Starclip]---MALAGA (WA)",
    "MYELEC[Starclip]---MIDLAND (WA)",
    "MYELEC[Starclip]---OSBORNE PARK (WA)",
    "MYELEC[Starclip]---WANGARA (WA)",
    "MYELEC[Starclip]---WELSHPOOL (WA)",
    "Netelec Electrical Supplies",
    "REXEL---ALBANY (WA)",
    "REXEL---BUNBURY (WA)",
    "REXEL---GERALDTON (WA)",
    "REXEL---KALGOORLIE (WA)",
    "REXEL---MALAGA (WA)",
    "REXEL---MYAREE (WA)",
    "REXEL---O'connor (WA)",
    "REXEL---OSBORNE PARK (WA)",
    "REXEL---PORT HEDLAND (WA)",
    "REXEL---WANGARA (WA)",
    "REXEL---WELSHPOOL (WA)",
    "Starclip Enterprises Pty Ltd",
    "Tradezone WA",
    "Uniquip Electrical Supplies - BIBRA LAKE",
    "Uniquip Electrical Supplies - WANGARA",
    "Uniquip Electrical Supplies - WELSHPOOL",
    "Uniquip Electrical Supplies",
    "WAIEW---CANNING VALE (WA)"

  ],
  TAS: [
    "Blackwoods Hobart",
    "Cash Sale TAS",
    "CNW Pty Ltd---HOBART (TAS)",
    "CNW Pty Ltd---LAUNCESTON (TAS)",
    "Halleys Lampland",
    "Haneco Lighting Internal Use TAS",
    "L&H[AUSLEC]---HOBART (TAS)",
    "L&H---BURNIE (TAS)",
    "L&H---DEVONPORT {DLQ} (TAS)",
    "L&H---HOBART (TAS)",
    "L&H---LAUNCESTON{DMB} (TAS)",
    "MIDDYS---HOBART (TAS)",
    "MIDDYS---HOBART EASTERN SHORE (TAS)",
    "MIDDYS---KINGSTON (TAS)",
    "MIDDYS---LAUNCESTON (TAS)",
    "MMEM[AWM]---BURNIE (TAS)",
    "MMEM[AWM]---LAUNCESTON (TAS)",
    "MMEM[AWM]---NORTH HOBART (TAS)",
    "MMEM[D&W]---DEVONPORT (TAS)",
    "MMEM[D&W]---HOBART (TAS)",
    "MMEM[D&W]---KINGSTON (TAS)",
    "MMEM[D&W]---LAUNCESTON (TAS)",
    "MMEM[D&W]---MORNINGTON (TAS)",
    "MMEM[EWM]---NORTH HOBART (TAS)",
    "MMEM[P&A]---LAUNCESTON (TAS)",
    "REXEL---BURNIE SOUTH (TAS)",
    "REXEL---CAMBRIDGE (TAS)",
    "REXEL---DERWENT PARK (TAS)",
    "REXEL---Devonport (TAS)",
    "REXEL---Launceston (TAS)",
    "REXEL---NORTH HOBART (TAS)",
    "ROBERT FERGUSSON---DEVONPORT (TAS)",
    "SHERRIFF---HOBART (TAS)",
    "Topstay HBT Pty Ltd Hobart",
    "Topstay HBT Pty Ltd Launceston"
  ],
  NT: [
    "Blackwoods Darwin",
    "Cash Sale NT",
    "CNW Pty Ltd---BERRIMAH (NT)",
    "CNW Pty Ltd---DARWIN (NT)",
    "ESS - Electrical Supply Solutions",
    "ESS---Berrimah (NT)",
    "Haneco Lighting Internal Use NT",
    "ISAS - Integrated Switchgear and Systems Pty Ltd",
    "JOHN R TURK---PALMERSTON (NT)",
    "L&H---Alice Springs {DRA} (NT)",
    "L&H---Darwin (NT)",
    "L&H---KATHERINE {DRJ} (NT)",
    "L&H---KUNUNURRA (WA)",
    "L&H---PALMERSTON (NT)",
    "MIDDYS---COOLALINGA (NT)",
    "MIDDYS---DARWIN (NT)",
    "MIDDYS---PALMERSTON (NT)",
    "MMEM[AWM]---WINNELLIE (NT)",
    "MMEM[HAYMANS]---Darwin (NT)",
    "MMEM[HAYMANS]---Winnellie (NT)",
    "MMEM---Alice Springs (NT)",
    "MMEM---KATHERINE (NT)",
    "MMEM---KATHERINE (NT)",
    "MMEM---PALMERSTON (NT)",
    "MMEM---WINNELLIE (NT)",
    "MMEM---Yarrawonga (NT)",
    "REXEL---DARWIN (NT)",
    "REXEL---PALMERSTON (NT)"

  ],
  ACT: [
    "Cash Sale ACT",
    "CNW Pty Ltd---FYSHWICK (ACT)",
    "George Brown Electrical",
    "Haneco Lighting Internal Use ACT",
    "JOHN R TURK---FYSHWICK (ACT)",
    "JOHN R TURK---MITCHELL (ACT)",
    "L&H[PDC]---CANBERRA(ACT)",
    "L&H---CANBERRA{DHI} (ACT)",
    "L&H---FYSHWICK {DFP} (ACT)",
    "L&H---MITCHELL {DGB} (ACT)",
    "MIDDYS---FYSHWICK (ACT)",
    "MMEM[TLE]---BELCONNEN (ACT)",
    "MMEM[TLE]---FYSHWICK (ACT)",
    "MMEM[TLE]---KAMBAH (ACT)",
    "PDC---FYSHWICK (ACT)",
    "POPES",
    "POPES---Commercial Division",
    "POPES---FYSHWICK (ACT)",
    "POPES---MITCHELL (ACT)",
    "POPES---PHILLIP (ACT)",
    "PROJECT LIGHTING PTY LTD---BELCONNEN (ACT)",
    "PROJECT LIGHTING PTY LTD---PHILLIP (ACT)",
    "PROJECT LIGHTING PTY LTD---QUEANBEYAN (ACT)",
    "PROJECT LIGHTING PTY LTD---TUGGERANONG (ACT)"

  ],
  FNQ:[
    "CNW Pty Ltd---CAIRNS (QLD)",
    "CNW Pty Ltd---GLADSTONE (QLD)",
    "CNW Pty Ltd---MACKAY (QLD)",
    "CNW Pty Ltd---TOWNSVILLE (QLD)",
    "Haneco Lighting Internal Use FNQ",
    "L&H[AUSLEC]---GLADSTONE (QLD)",
    "L&H---AYR {DAA} (QLD)",
    "L&H---CAIRNS (QLD)",
    "L&H---EMERALD (QLD)",
    "L&H---MACKAY (QLD)",
    "L&H---ROCKHAMPTON (QLD)",
    "L&H---Townsville (QLD)",
    "MMEM[Greentech]---Cairns (QLD)",
    "MMEM[Greentech]---Maroochydore (QLD)",
    "MMEM[Greentech]---Townsville (QLD)",
    "MMEM[HAYMANS]---Cairns {Bungalow} (QLD)",
    "MMEM[HAYMANS]---Fairfield (QLD)",
    "MMEM[HAYMANS]---GARBUTT (QLD)",
    "MMEM[HAYMANS]---Gladstone (QLD)",
    "MMEM[HAYMANS]---MACKAY (QLD)",
    "MMEM[HAYMANS]---Mareeba (QLD)",
    "MMEM[HAYMANS]---Port Douglas {Craiglie} (QLD)",
    "MMEM[HAYMANS]---Rockhampton (QLD)",
    "MMEM---MACKAY (QLD)",
    "REXEL[IES]---INNISFAIL (QLD)",
    "REXEL[IES]---TOWNSVILLE (QLD)",
    "REXEL---MACKAY (QLD)",
    "REXEL---TOOWOOMBA (QLD)",
    "SHERRIFF---CAIRNS (QLD)",
    "SHERRIFF---GLADSTONE (QLD)",
    "SHERRIFF---INFRASTRUCTURE {GARBUTT} (QLD)",
    "SHERRIFF---MACKAY (QLD)",
    "SHERRIFF---TOWNSVILLE (QLD)",
    "THE LIGHT HOUSE-----CAIRNS (QLD)"

  ]
};
